### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by Rayquaza01** [Rayquaza01/note-taker#1]
New features to be added in next version
- [x] Sidebar
- [x] Per-Site mode
- [x] Better text box resizing
- [x] Color and Font settings
- [x] Autofocus text box

**Comment by 2SI3NX** [comment]
Thanks for this. Its very much needed. Simplicity is key.  Per site or per tab notes is one of the most important things that you could do on this addon for your users, it would be very helpful.

**Comment by v-marinkov** [comment]
I would like to second the need for per site (url) notes. I tend to keep many 100s of opened tabs and a simple text note-to-self for why I kept a particular tab is invaluable!

**Comment by Rayquaza01** [comment]
The new version is (mostly) ready. I'm going to wait a while before submitting it to AMO to make sure I didn't miss anything. It's available [here](https://github.com/Rayquaza01/note-taker/blob/master/note_taker-1.1rc-an+fx.xpi?raw=true) for the time being. If anyone notices any mistakes or problems with the version, make sure to submit an issue.

**Comment by Rayquaza01** [comment]
Version 1.1 is now officially available on AMO.
