### ISSUE TITLE
Problem: Note taker doesn't support Right-To-Left Direction

### ISSUE THREAD

**Issue by mstfelq** [Rayquaza01/note-taker#10]
In many languages (e. g: Arabic, Hebrew and Persian) the direction of writing is from Right to Left. I always use note taker in taking notes in Arabic language, please consider adding this option to note taker. Thank you for this helpful addon!

**Comment by Rayquaza01** [comment]
This should be addressed in the newest version (1.2.3). There is a new option for Text Direction. It defaults to Left to Right, but can be set to Right to Left.
