### ISSUE TITLE
Badges broken in 1.2.6?

### ISSUE THREAD

**Issue by seascape** [Rayquaza01/note-taker#16]
## Bug Report

Please fill out this information:
 * Browser version: FF 64.0
 * Extension version: 1.2.6
 * Operating system: Win10 LTSB 2016

---

What is happening?
Badges no longer appear on the Standard Notes icon when a URL/domain has associated notes.

---

What are the steps to reproduce the bug?
Unclear. I tried the various different badge display types and all showed nothing.

Are you seeing it on your end? If not I can examine my setup more closely. My userchrome.css is pretty customized but deleting it did not bring badges back.

**Comment by oositP** [comment]
Yes im having the same problem in Firefox latest on Ubuntu!
This is definitely a bug from latest update, as it worked before. Please fix!

**Comment by Rayquaza01** [comment]
@oositP @seascape 
Ok, this is actually a pretty easy fix, I'll publish an update ASAP. Essentially, I changed around some things in the site parser, but I forgot to reflect those changes in the badge code.

Specifically, [setup.js line 110](https://github.com/Rayquaza01/note-taker/blob/a8278e40638e62aba9f9825cc3ec7048347ae6cc/extension/setup.js#L110)
Currently it is `let site = siteParser(tab.url, res.options.default_display, res);`  
And it should be `let site = siteParser(tab.url, res);`

**Comment by seascape** [comment]
Confirmed fixed. Thank you!
