### ISSUE TITLE
Does not switch site URL's when switching between TABS to write notes

### ISSUE THREAD

**Issue by 2SI3NX** [Rayquaza01/note-taker#2]
As the heading states, if i write a note about a URL tab, and i switch to another tab to write a note, it does not switch to the other tab's URL at the bottom, it shows the same note as the first URL tab.

**Comment by Rayquaza01** [comment]
This should be addressed in the newest version of the extension (v1.1.1) which is currently available on AMO.

**Comment by 2SI3NX** [comment]
Perfect, this is fixed!
