### ISSUE TITLE
Bug: Wrong text in "Manage Extension Shortcuts"

### ISSUE THREAD

**Issue by ReporterX** [Rayquaza01/note-taker#25]
* Browser version: 66.03
 * Extension version: 1.2.7
 * Operating system: Windows 7

Steps to reproduce:
Go to addons > Manage extension shortcuts.

I believe the name of the first shortcut is wrong. It should be called **Toggle the popup**.

![screenshot 1](https://user-images.githubusercontent.com/8235338/56488081-e3aa1480-650f-11e9-8af8-a1e4e048e622.jpg)

It would be better if names on both sides are consistent.
I would suggest calling "**Toggle Popup**" and "**Toggle Sidebar**" respectively.

![screenshot 2](https://user-images.githubusercontent.com/8235338/56488223-5e732f80-6510-11e9-99f7-f0913c12492c.jpg)

**Comment by Rayquaza01** [comment]
Sorry for not getting to this sooner.
I can't control the text that displays on the Manage Extension Shortcuts page, that's generated by Firefox. I could change "Popup Shortcut" to "Activate Extension" on the options page, but I don't think that would be a useful change.
