### ISSUE TITLE
Enhancement:  Icon Notification

### ISSUE THREAD

**Issue by 2SI3NX** [Rayquaza01/note-taker#3]
This notification would have to show like a small number on it, to show that there is a note taken when you re-open a specific URL for site specific URLs.

The small number would look like just as the HTTPS Everywhere addon icon has when it encrypts sites, it has numbers on the blue icon S.

Thank you so much for such an awesome addon!!! this is such a time saver and organizer!

**Comment by 2SI3NX** [comment]
Also, maybe you can allow bullet points to be activated by default if the user wishes.  And each bullet point will be the number of notes taken which will = the icon numbers shown. 
eg.
if there are 4 bullet points in a site specific URL, then when checking the icon, it will show the small number 4 in the top right or bottom right corner. To show that 4 notes have been taken for that specific site URL.

**Comment by Rayquaza01** [comment]
Thanks for the suggestion. I worked on it a bit, and I think it's going to be a very useful feature. It will definitely be added soon.

![image](https://user-images.githubusercontent.com/22138871/31572010-5141362e-b06a-11e7-9ae9-5a467e82b9be.png)
![image](https://user-images.githubusercontent.com/22138871/31572011-581334ca-b06a-11e7-8aa4-72d15ccbbf4a.png)

**Comment by 2SI3NX** [comment]
wow thats really awesome and useful!!

**Comment by Rayquaza01** [comment]
Notification badges have been added in version 1.1.2, now available on AMO. They're disabled by default, so you need to activate them on the options page.

**Comment by 2SI3NX** [comment]
I see that it works great! Awesome thank you
