### ISSUE TITLE
Request : Text Box - Padding Option via Settings

### ISSUE THREAD

**Issue by g-enriquez** [Rayquaza01/note-taker#4]
Option to add a padding for the Text Box (similar to font-size/width-height adjustment). It looks good and minimalistic as it is now, just thought that adding a padding for the Text Box would make it nicer to look at.

If you can't add it as an option, could you maybe make it a default style with about 5 ~ 10px padding for the Text Box?

Thanks and Good Job for making this add-on!

**Comment by Rayquaza01** [comment]
Sorry for not getting to this sooner.

A padding option has been added in the new version (1.2.0) released today. The default value is 5px.

**Comment by g-enriquez** [comment]
Looking good now. Thanks!
