### ISSUE TITLE
All notes are gone. Where does note-taker store notes?

### ISSUE THREAD

**Issue by bege10** [Rayquaza01/note-taker#44]
## Question

All notes in note-taker are gone. I need to know the storage location to restore them from a backup.
I don't know when this happened because I didn't look for the notes for quite a while.
This #36 closed issue does not solve mine.
The problem with vanished notes is also mentioned a few times in the feedbacks on AMO.

**Comment by Rayquaza01** [comment]
Hello,
I'm very sorry that you lost your notes! Note Taker stores notes using the Webextension Storage API. The actual data on disk is stored in `[firefox profile folder]/storage/default/moz-extension+++[extension uuid]^userContextId=4294967295/idb/3647222921wleabcEoxlt-eengsairo.sqlite` ([1](https://stackoverflow.com/questions/65448110/where-are-the-data-for-extension-storage-of-a-firefox-extension-stored-in)). It should be noted that this SQLite file is compressed, so unless you know what you're doing you can't edit it directly. You should be able to restore from a backup, though.

If you don't know your Firefox profile location, you can find it listed on `about:support`. To find Note Taker's uuid, go to `about:debugging`, switch to the "This Firefox" tab, and find Note Taker on the list. The value you want is labeled "Internal UUID".

**Comment by bege10** [comment]
Thank you for your answer. I found the database. 👍
