### ISSUE TITLE
Enhancement: make Site mode - toggle button URL/Domain

### ISSUE THREAD

**Issue by ghost** [Rayquaza01/note-taker#6]
It would be easier to have a toggle button to allow notes either for URL/domain

ps: thanks for a convenient addon!

**Comment by 2SI3NX** [comment]
BTW would this work though? i mean if its defaulted to URL, but toggle to domain and make a note for a certain domain, will there be a notification that there was a note taken if you go to that site again and its defaulted back to URL?
