### ISSUE TITLE
Sync / Online storage

### ISSUE THREAD

**Issue by allibragi** [Rayquaza01/note-taker#8]
Possibility to sync notes through different devices or save them in the cloud.

**Comment by Rayquaza01** [comment]
Sorry for not getting to this sooner.

As of the latest version (1.2.0) released today, there are two buttons on the options page for saving and restoring notes and options to and from sync. I don't have a very good way of testing sync between multiple devices right now, so I can't be sure that nothing will break if I make it automatic.

Also I recommend manually exporting options and notes before restoring from sync, just in case it doesn't work properly.

**Comment by allibragi** [comment]
Sync is working, at least for me.
You need to remember which device is the most updated but i currently use the plugin only on 2 pc, so it's ok.
